//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//       生成时间 2015-06-15 16:35:22 by YmNets
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using CLZ.Common;
using CLZ.Model;
using CLZ.Model.common;
using CLZ.Model.Sys;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.ServiceModel;
using System.ServiceModel.Web;
using System.Text;
namespace App.Sys
{
    // 注意: 使用“重构”菜单上的“重命名”命令，可以同时更改代码和配置文件中的接口名“IService1”。
    [ServiceContract]
    public interface ICommonService
    {

        // TODO: 在此添加您的服务操作

		#region SysException
		[OperationContract]
		List<SysException> getAllSysException();
		[OperationContract]
		int AddSysException(SysException model,ref ValidationError error);
		[OperationContract]
        SysException geSysExceptionById(int id);
		[OperationContract]
        int Edit(SysException model,ref ValidationError error);
		[OperationContract]
        int Delete(int id, ref ValidationError error);
		[OperationContract]
        List<SysException> GetList(ref GridPager pager);
		#endregion

		#region SysLog
		[OperationContract]
		List<SysLog> getAllSysLog();
		[OperationContract]
		int AddSysLog(SysLog model,ref ValidationError error);
		[OperationContract]
        SysLog geSysLogById(int id);
		[OperationContract]
        int Edit(SysLog model,ref ValidationError error);
		[OperationContract]
        int Delete(int id, ref ValidationError error);
		[OperationContract]
        List<SysLog> GetList(ref GridPager pager);
		#endregion

		#region SysModule
		[OperationContract]
		List<SysModule> getAllSysModule();
		[OperationContract]
		int AddSysModule(SysModule model,ref ValidationError error);
		[OperationContract]
        SysModule geSysModuleById(int id);
		[OperationContract]
        int Edit(SysModule model,ref ValidationError error);
		[OperationContract]
        int Delete(int id, ref ValidationError error);
		[OperationContract]
        List<SysModule> GetList(ref GridPager pager);
		#endregion

		#region SysModuleOperate
		[OperationContract]
		List<SysModuleOperate> getAllSysModuleOperate();
		[OperationContract]
		int AddSysModuleOperate(SysModuleOperate model,ref ValidationError error);
		[OperationContract]
        SysModuleOperate geSysModuleOperateById(int id);
		[OperationContract]
        int Edit(SysModuleOperate model,ref ValidationError error);
		[OperationContract]
        int Delete(int id, ref ValidationError error);
		[OperationContract]
        List<SysModuleOperate> GetList(ref GridPager pager);
		#endregion

		#region SysRight
		[OperationContract]
		List<SysRight> getAllSysRight();
		[OperationContract]
		int AddSysRight(SysRight model,ref ValidationError error);
		[OperationContract]
        SysRight geSysRightById(int id);
		[OperationContract]
        int Edit(SysRight model,ref ValidationError error);
		[OperationContract]
        int Delete(int id, ref ValidationError error);
		[OperationContract]
        List<SysRight> GetList(ref GridPager pager);
		#endregion

		#region SysRightOperate
		[OperationContract]
		List<SysRightOperate> getAllSysRightOperate();
		[OperationContract]
		int AddSysRightOperate(SysRightOperate model,ref ValidationError error);
		[OperationContract]
        SysRightOperate geSysRightOperateById(int id);
		[OperationContract]
        int Edit(SysRightOperate model,ref ValidationError error);
		[OperationContract]
        int Delete(int id, ref ValidationError error);
		[OperationContract]
        List<SysRightOperate> GetList(ref GridPager pager);
		#endregion

		#region SysRole
		[OperationContract]
		List<SysRole> getAllSysRole();
		[OperationContract]
		int AddSysRole(SysRole model,ref ValidationError error);
		[OperationContract]
        SysRole geSysRoleById(int id);
		[OperationContract]
        int Edit(SysRole model,ref ValidationError error);
		[OperationContract]
        int Delete(int id, ref ValidationError error);
		[OperationContract]
        List<SysRole> GetList(ref GridPager pager);
		#endregion

		#region SysRoleSysUser
		[OperationContract]
		List<SysRoleSysUser> getAllSysRoleSysUser();
		[OperationContract]
		int AddSysRoleSysUser(SysRoleSysUser model,ref ValidationError error);
		[OperationContract]
        SysRoleSysUser geSysRoleSysUserById(int id);
		[OperationContract]
        int Edit(SysRoleSysUser model,ref ValidationError error);
		[OperationContract]
        int Delete(int id, ref ValidationError error);
		[OperationContract]
        List<SysRoleSysUser> GetList(ref GridPager pager);
		#endregion

		#region SysSample
		[OperationContract]
		List<SysSample> getAllSysSample();
		[OperationContract]
		int AddSysSample(SysSample model,ref ValidationError error);
		[OperationContract]
        SysSample geSysSampleById(int id);
		[OperationContract]
        int Edit(SysSample model,ref ValidationError error);
		[OperationContract]
        int Delete(int id, ref ValidationError error);
		[OperationContract]
        List<SysSample> GetList(ref GridPager pager);
		#endregion

		#region SysUser
		[OperationContract]
		List<SysUser> getAllSysUser();
		[OperationContract]
		int AddSysUser(SysUser model,ref ValidationError error);
		[OperationContract]
        SysUser geSysUserById(int id);
		[OperationContract]
        int Edit(SysUser model,ref ValidationError error);
		[OperationContract]
        int Delete(int id, ref ValidationError error);
		[OperationContract]
        List<SysUser> GetList(ref GridPager pager);
		#endregion

		#region test
		[OperationContract]
		List<test> getAlltest();
		[OperationContract]
		int Addtest(test model,ref ValidationError error);
		[OperationContract]
        test getestById(int id);
		[OperationContract]
        int Edit(test model,ref ValidationError error);
		[OperationContract]
        int Delete(int id, ref ValidationError error);
		[OperationContract]
        List<test> GetList(ref GridPager pager);
		#endregion

		#region wx_product
		[OperationContract]
		List<wx_product> getAllwx_product();
		[OperationContract]
		int Addwx_product(wx_product model,ref ValidationError error);
		[OperationContract]
        wx_product gewx_productById(int id);
		[OperationContract]
        int Edit(wx_product model,ref ValidationError error);
		[OperationContract]
        int Delete(int id, ref ValidationError error);
		[OperationContract]
        List<wx_product> GetList(ref GridPager pager);
		#endregion

		#region wx_product_cart
		[OperationContract]
		List<wx_product_cart> getAllwx_product_cart();
		[OperationContract]
		int Addwx_product_cart(wx_product_cart model,ref ValidationError error);
		[OperationContract]
        wx_product_cart gewx_product_cartById(int id);
		[OperationContract]
        int Edit(wx_product_cart model,ref ValidationError error);
		[OperationContract]
        int Delete(int id, ref ValidationError error);
		[OperationContract]
        List<wx_product_cart> GetList(ref GridPager pager);
		#endregion

		#region wx_product_cat
		[OperationContract]
		List<wx_product_cat> getAllwx_product_cat();
		[OperationContract]
		int Addwx_product_cat(wx_product_cat model,ref ValidationError error);
		[OperationContract]
        wx_product_cat gewx_product_catById(int id);
		[OperationContract]
        int Edit(wx_product_cat model,ref ValidationError error);
		[OperationContract]
        int Delete(int id, ref ValidationError error);
		[OperationContract]
        List<wx_product_cat> GetList(ref GridPager pager);
		#endregion

		#region wx_product_salegoods
		[OperationContract]
		List<wx_product_salegoods> getAllwx_product_salegoods();
		[OperationContract]
		int Addwx_product_salegoods(wx_product_salegoods model,ref ValidationError error);
		[OperationContract]
        wx_product_salegoods gewx_product_salegoodsById(int id);
		[OperationContract]
        int Edit(wx_product_salegoods model,ref ValidationError error);
		[OperationContract]
        int Delete(int id, ref ValidationError error);
		[OperationContract]
        List<wx_product_salegoods> GetList(ref GridPager pager);
		#endregion


	}
}

