







//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//       生成时间 2015-06-30 11:15:14 by Ye Fenglei
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using CLZ.Common;
using CLZ.Model;
using CLZ.Model.common;
using CLZ.Model.Sys;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.ServiceModel;
using System.ServiceModel.Web;
using System.Text;

namespace CLZ.Service
{
    // 注意: 使用“重构”菜单上的“重命名”命令，可以同时更改代码和配置文件中的接口名“IService1”。
    [ServiceContract]
    public interface ICommonService
    {        
	// TODO: 在此添加您的服务操作

		#region SysSample
		[OperationContract]
		List<SysSample> getAllSysSample();
		[OperationContract]
		int AddSysSample(SysSample model,ref ValidationError error);
		[OperationContract]
        SysSample getSysSampleById(Int32 Id);
		[OperationContract]
        int EditSysSample(SysSample model,ref ValidationError error);
		[OperationContract]

        int DeleteSysSample(Int32 Id, ref ValidationError error);
		[OperationContract]
        List<SysSample> GetSysSampleList(ref GridPager pager);

		#endregion


		#region ZH_GOODS_TYPE
		[OperationContract]
		List<ZH_GOODS_TYPE> getAllZH_GOODS_TYPE();
		[OperationContract]
		int AddZH_GOODS_TYPE(ZH_GOODS_TYPE model,ref ValidationError error);
		[OperationContract]
        ZH_GOODS_TYPE getZH_GOODS_TYPEById(Int32 ID);
		[OperationContract]
        int EditZH_GOODS_TYPE(ZH_GOODS_TYPE model,ref ValidationError error);
		[OperationContract]

        int DeleteZH_GOODS_TYPE(Int32 ID, ref ValidationError error);
		[OperationContract]
        List<ZH_GOODS_TYPE> GetZH_GOODS_TYPEList(ref GridPager pager);

		#endregion


		#region test
		[OperationContract]
		List<test> getAlltest();
		[OperationContract]
		int Addtest(test model,ref ValidationError error);
		[OperationContract]
        test gettestById(Int32 Id);
		[OperationContract]
        int Edittest(test model,ref ValidationError error);
		[OperationContract]

        int Deletetest(Int32 Id, ref ValidationError error);
		[OperationContract]
        List<test> GettestList(ref GridPager pager);

		#endregion


		#region ZH_DIC_PRODUCT
		[OperationContract]
		List<ZH_DIC_PRODUCT> getAllZH_DIC_PRODUCT();
		[OperationContract]
		int AddZH_DIC_PRODUCT(ZH_DIC_PRODUCT model,ref ValidationError error);
		[OperationContract]
        ZH_DIC_PRODUCT getZH_DIC_PRODUCTById(String PRODUCT_SN);
		[OperationContract]
        int EditZH_DIC_PRODUCT(ZH_DIC_PRODUCT model,ref ValidationError error);
		[OperationContract]

        int DeleteZH_DIC_PRODUCT(String PRODUCT_SN, ref ValidationError error);
		[OperationContract]
        List<ZH_DIC_PRODUCT> GetZH_DIC_PRODUCTList(ref GridPager pager);

		#endregion


		#region SysModule
		[OperationContract]
		List<SysModule> getAllSysModule();
		[OperationContract]
		int AddSysModule(SysModule model,ref ValidationError error);
		[OperationContract]
        SysModule getSysModuleById(String Id);
		[OperationContract]
        int EditSysModule(SysModule model,ref ValidationError error);
		[OperationContract]

        int DeleteSysModule(String Id, ref ValidationError error);
		[OperationContract]
        List<SysModule> GetSysModuleList(ref GridPager pager);

		#endregion


		#region wx_service_points
		[OperationContract]
		List<wx_service_points> getAllwx_service_points();
		[OperationContract]
		int Addwx_service_points(wx_service_points model,ref ValidationError error);
		[OperationContract]
        wx_service_points getwx_service_pointsById(Int32 Id);
		[OperationContract]
        int Editwx_service_points(wx_service_points model,ref ValidationError error);
		[OperationContract]

        int Deletewx_service_points(Int32 Id, ref ValidationError error);
		[OperationContract]
        List<wx_service_points> Getwx_service_pointsList(ref GridPager pager);

		#endregion


		#region SysLog
		[OperationContract]
		List<SysLog> getAllSysLog();
		[OperationContract]
		int AddSysLog(SysLog model,ref ValidationError error);
		[OperationContract]
        SysLog getSysLogById(String Id);
		[OperationContract]
        int EditSysLog(SysLog model,ref ValidationError error);
		[OperationContract]

        int DeleteSysLog(String Id, ref ValidationError error);
		[OperationContract]
        List<SysLog> GetSysLogList(ref GridPager pager);

		#endregion


		#region SysException
		[OperationContract]
		List<SysException> getAllSysException();
		[OperationContract]
		int AddSysException(SysException model,ref ValidationError error);
		[OperationContract]
        SysException getSysExceptionById(String Id);
		[OperationContract]
        int EditSysException(SysException model,ref ValidationError error);
		[OperationContract]

        int DeleteSysException(String Id, ref ValidationError error);
		[OperationContract]
        List<SysException> GetSysExceptionList(ref GridPager pager);

		#endregion


		#region SysModuleOperate
		[OperationContract]
		List<SysModuleOperate> getAllSysModuleOperate();
		[OperationContract]
		int AddSysModuleOperate(SysModuleOperate model,ref ValidationError error);
		[OperationContract]
        SysModuleOperate getSysModuleOperateById(String Id);
		[OperationContract]
        int EditSysModuleOperate(SysModuleOperate model,ref ValidationError error);
		[OperationContract]

        int DeleteSysModuleOperate(String Id, ref ValidationError error);
		[OperationContract]
        List<SysModuleOperate> GetSysModuleOperateList(ref GridPager pager);

		#endregion


		#region SysRole
		[OperationContract]
		List<SysRole> getAllSysRole();
		[OperationContract]
		int AddSysRole(SysRole model,ref ValidationError error);
		[OperationContract]
        SysRole getSysRoleById(String Id);
		[OperationContract]
        int EditSysRole(SysRole model,ref ValidationError error);
		[OperationContract]

        int DeleteSysRole(String Id, ref ValidationError error);
		[OperationContract]
        List<SysRole> GetSysRoleList(ref GridPager pager);

		#endregion


		#region SysUser
		[OperationContract]
		List<SysUser> getAllSysUser();
		[OperationContract]
		int AddSysUser(SysUser model,ref ValidationError error);
		[OperationContract]
        SysUser getSysUserById(String Id);
		[OperationContract]
        int EditSysUser(SysUser model,ref ValidationError error);
		[OperationContract]

        int DeleteSysUser(String Id, ref ValidationError error);
		[OperationContract]
        List<SysUser> GetSysUserList(ref GridPager pager);

		#endregion


		#region SysRoleSysUser
		[OperationContract]
		List<SysRoleSysUser> getAllSysRoleSysUser();
		[OperationContract]
		int AddSysRoleSysUser(SysRoleSysUser model,ref ValidationError error);
		[OperationContract]
        SysRoleSysUser getSysRoleSysUserById(String SysUserId,String SysRoleId);
		[OperationContract]
        int EditSysRoleSysUser(SysRoleSysUser model,ref ValidationError error);
		[OperationContract]

        int DeleteSysRoleSysUser(String SysUserId,String SysRoleId, ref ValidationError error);
		[OperationContract]
        List<SysRoleSysUser> GetSysRoleSysUserList(ref GridPager pager);

		#endregion


		#region SysRight
		[OperationContract]
		List<SysRight> getAllSysRight();
		[OperationContract]
		int AddSysRight(SysRight model,ref ValidationError error);
		[OperationContract]
        SysRight getSysRightById(String Id);
		[OperationContract]
        int EditSysRight(SysRight model,ref ValidationError error);
		[OperationContract]

        int DeleteSysRight(String Id, ref ValidationError error);
		[OperationContract]
        List<SysRight> GetSysRightList(ref GridPager pager);

		#endregion


		#region SysRightOperate
		[OperationContract]
		List<SysRightOperate> getAllSysRightOperate();
		[OperationContract]
		int AddSysRightOperate(SysRightOperate model,ref ValidationError error);
		[OperationContract]
        SysRightOperate getSysRightOperateById(String Id);
		[OperationContract]
        int EditSysRightOperate(SysRightOperate model,ref ValidationError error);
		[OperationContract]

        int DeleteSysRightOperate(String Id, ref ValidationError error);
		[OperationContract]
        List<SysRightOperate> GetSysRightOperateList(ref GridPager pager);

		#endregion


		#region wx_product_cart
		[OperationContract]
		List<wx_product_cart> getAllwx_product_cart();
		[OperationContract]
		int Addwx_product_cart(wx_product_cart model,ref ValidationError error);
		[OperationContract]
        wx_product_cart getwx_product_cartById(Int64 id);
		[OperationContract]
        int Editwx_product_cart(wx_product_cart model,ref ValidationError error);
		[OperationContract]

        int Deletewx_product_cart(Int64 id, ref ValidationError error);
		[OperationContract]
        List<wx_product_cart> Getwx_product_cartList(ref GridPager pager);

		#endregion


		#region wx_product_salegoods
		[OperationContract]
		List<wx_product_salegoods> getAllwx_product_salegoods();
		[OperationContract]
		int Addwx_product_salegoods(wx_product_salegoods model,ref ValidationError error);
		[OperationContract]
        wx_product_salegoods getwx_product_salegoodsById(Int64 id);
		[OperationContract]
        int Editwx_product_salegoods(wx_product_salegoods model,ref ValidationError error);
		[OperationContract]

        int Deletewx_product_salegoods(Int64 id, ref ValidationError error);
		[OperationContract]
        List<wx_product_salegoods> Getwx_product_salegoodsList(ref GridPager pager);

		#endregion


		#region wx_product
		[OperationContract]
		List<wx_product> getAllwx_product();
		[OperationContract]
		int Addwx_product(wx_product model,ref ValidationError error);
		[OperationContract]
        wx_product getwx_productById(Int32 id);
		[OperationContract]
        int Editwx_product(wx_product model,ref ValidationError error);
		[OperationContract]

        int Deletewx_product(Int32 id, ref ValidationError error);
		[OperationContract]
        List<wx_product> Getwx_productList(ref GridPager pager);

		#endregion


		#region wx_product_cat
		[OperationContract]
		List<wx_product_cat> getAllwx_product_cat();
		[OperationContract]
		int Addwx_product_cat(wx_product_cat model,ref ValidationError error);
		[OperationContract]
        wx_product_cat getwx_product_catById(Int32 id);
		[OperationContract]
        int Editwx_product_cat(wx_product_cat model,ref ValidationError error);
		[OperationContract]

        int Deletewx_product_cat(Int32 id, ref ValidationError error);
		[OperationContract]
        List<wx_product_cat> Getwx_product_catList(ref GridPager pager);

		#endregion


		#region ZH_DAILY_GOODS_DEAL
		[OperationContract]
		List<ZH_DAILY_GOODS_DEAL> getAllZH_DAILY_GOODS_DEAL();
		[OperationContract]
		int AddZH_DAILY_GOODS_DEAL(ZH_DAILY_GOODS_DEAL model,ref ValidationError error);
		[OperationContract]
        ZH_DAILY_GOODS_DEAL getZH_DAILY_GOODS_DEALById(String ID);
		[OperationContract]
        int EditZH_DAILY_GOODS_DEAL(ZH_DAILY_GOODS_DEAL model,ref ValidationError error);
		[OperationContract]

        int DeleteZH_DAILY_GOODS_DEAL(String ID, ref ValidationError error);
		[OperationContract]
        List<ZH_DAILY_GOODS_DEAL> GetZH_DAILY_GOODS_DEALList(ref GridPager pager);

		#endregion


		#region ZH_SETTLE_DEAL_MAIN
		[OperationContract]
		List<ZH_SETTLE_DEAL_MAIN> getAllZH_SETTLE_DEAL_MAIN();
		[OperationContract]
		int AddZH_SETTLE_DEAL_MAIN(ZH_SETTLE_DEAL_MAIN model,ref ValidationError error);
		[OperationContract]
        ZH_SETTLE_DEAL_MAIN getZH_SETTLE_DEAL_MAINById(Int64 ID);
		[OperationContract]
        int EditZH_SETTLE_DEAL_MAIN(ZH_SETTLE_DEAL_MAIN model,ref ValidationError error);
		[OperationContract]

        int DeleteZH_SETTLE_DEAL_MAIN(Int64 ID, ref ValidationError error);
		[OperationContract]
        List<ZH_SETTLE_DEAL_MAIN> GetZH_SETTLE_DEAL_MAINList(ref GridPager pager);

		#endregion

	}
}