//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//       生成时间 2015-06-15 16:22:06 by YmNets
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace App.Sys
{    

    public class SysSampleModel
    {
                public int Id { get; set; }
                public string Name { get; set; }
                public int? Age { get; set; }
                public DateTime? Bir { get; set; }
                public string Photo { get; set; }
                public string Note { get; set; }
                public DateTime? CreateTime { get; set; }
         
    }
}
