//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLZ.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DBContainer : DbContext
    {
        public DBContainer()
            : base("name=DBContainer")
        {
            this.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SysException> SysException { get; set; }
        public virtual DbSet<SysLog> SysLog { get; set; }
        public virtual DbSet<SysModule> SysModule { get; set; }
        public virtual DbSet<SysModuleOperate> SysModuleOperate { get; set; }
        public virtual DbSet<SysRight> SysRight { get; set; }
        public virtual DbSet<SysRightOperate> SysRightOperate { get; set; }
        public virtual DbSet<SysRole> SysRole { get; set; }
        public virtual DbSet<SysSample> SysSample { get; set; }
        public virtual DbSet<SysUser> SysUser { get; set; }
        public virtual DbSet<wx_product> wx_product { get; set; }
        public virtual DbSet<wx_product_cart> wx_product_cart { get; set; }
        public virtual DbSet<wx_product_cat> wx_product_cat { get; set; }
        public virtual DbSet<wx_product_salegoods> wx_product_salegoods { get; set; }
        public virtual DbSet<wx_service_points> wx_service_points { get; set; }
        public virtual DbSet<ZH_DIC_PRODUCT> ZH_DIC_PRODUCT { get; set; }
        public virtual DbSet<ZH_GOODS_TYPE> ZH_GOODS_TYPE { get; set; }
        public virtual DbSet<ZH_SETTLE_DEAL_MAIN> ZH_SETTLE_DEAL_MAIN { get; set; }
        public virtual DbSet<wx_customer_order> wx_customer_order { get; set; }
        public virtual DbSet<ZH_DAILY_GOODS_DEAL> ZH_DAILY_GOODS_DEAL { get; set; }
        public virtual DbSet<easyui_query_parameters> easyui_query_parameters { get; set; }
        public virtual DbSet<univgrid> univgrid { get; set; }
        public virtual DbSet<univgrid_parameter> univgrid_parameter { get; set; }
        public virtual DbSet<univgrid_parameter_setup> univgrid_parameter_setup { get; set; }
        public virtual DbSet<easyuicolumn> easyuicolumn { get; set; }
        public virtual DbSet<highchart> highchart { get; set; }
        public virtual DbSet<highchart_column> highchart_column { get; set; }
        public virtual DbSet<easyuigrid> easyuigrid { get; set; }
    
        public virtual int P_Sys_ClearUnusedRightOperate()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_Sys_ClearUnusedRightOperate");
        }
    
        public virtual int P_Sys_DeleteSysRoleSysUserByRoleId(string roleId)
        {
            var roleIdParameter = roleId != null ?
                new ObjectParameter("roleId", roleId) :
                new ObjectParameter("roleId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_Sys_DeleteSysRoleSysUserByRoleId", roleIdParameter);
        }
    
        public virtual int P_Sys_DeleteSysRoleSysUserByUserId(string userId)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_Sys_DeleteSysRoleSysUserByUserId", userIdParameter);
        }
    
        public virtual ObjectResult<P_Sys_GetRightByRoleAndModule_Result> P_Sys_GetRightByRoleAndModule(string roleId, string moduleId)
        {
            var roleIdParameter = roleId != null ?
                new ObjectParameter("roleId", roleId) :
                new ObjectParameter("roleId", typeof(string));
    
            var moduleIdParameter = moduleId != null ?
                new ObjectParameter("moduleId", moduleId) :
                new ObjectParameter("moduleId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<P_Sys_GetRightByRoleAndModule_Result>("P_Sys_GetRightByRoleAndModule", roleIdParameter, moduleIdParameter);
        }
    
        public virtual ObjectResult<P_Sys_GetRightOperate_Result> P_Sys_GetRightOperate(string userId, string url)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(string));
    
            var urlParameter = url != null ?
                new ObjectParameter("url", url) :
                new ObjectParameter("url", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<P_Sys_GetRightOperate_Result>("P_Sys_GetRightOperate", userIdParameter, urlParameter);
        }
    
        public virtual ObjectResult<P_Sys_GetRoleByUserId_Result> P_Sys_GetRoleByUserId(string userId)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<P_Sys_GetRoleByUserId_Result>("P_Sys_GetRoleByUserId", userIdParameter);
        }
    
        public virtual ObjectResult<P_Sys_GetUserByRoleId_Result> P_Sys_GetUserByRoleId(string roleId)
        {
            var roleIdParameter = roleId != null ?
                new ObjectParameter("RoleId", roleId) :
                new ObjectParameter("RoleId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<P_Sys_GetUserByRoleId_Result>("P_Sys_GetUserByRoleId", roleIdParameter);
        }
    
        public virtual int P_Sys_InsertSysRight()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_Sys_InsertSysRight");
        }
    
        public virtual int P_Sys_UpdateSysRightRightFlag(string moduleId, string roleId)
        {
            var moduleIdParameter = moduleId != null ?
                new ObjectParameter("moduleId", moduleId) :
                new ObjectParameter("moduleId", typeof(string));
    
            var roleIdParameter = roleId != null ?
                new ObjectParameter("roleId", roleId) :
                new ObjectParameter("roleId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_Sys_UpdateSysRightRightFlag", moduleIdParameter, roleIdParameter);
        }
    
        public virtual int P_Sys_UpdateSysRoleSysUser(string roleId, string userId)
        {
            var roleIdParameter = roleId != null ?
                new ObjectParameter("roleId", roleId) :
                new ObjectParameter("roleId", typeof(string));
    
            var userIdParameter = userId != null ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_Sys_UpdateSysRoleSysUser", roleIdParameter, userIdParameter);
        }
    
        public virtual ObjectResult<sp_wx_getCustomerInfo_Result> sp_wx_getCustomerInfo(Nullable<System.DateTime> startTime, Nullable<System.DateTime> endTime, Nullable<int> timeSpan)
        {
            var startTimeParameter = startTime.HasValue ?
                new ObjectParameter("startTime", startTime) :
                new ObjectParameter("startTime", typeof(System.DateTime));
    
            var endTimeParameter = endTime.HasValue ?
                new ObjectParameter("endTime", endTime) :
                new ObjectParameter("endTime", typeof(System.DateTime));
    
            var timeSpanParameter = timeSpan.HasValue ?
                new ObjectParameter("timeSpan", timeSpan) :
                new ObjectParameter("timeSpan", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_wx_getCustomerInfo_Result>("sp_wx_getCustomerInfo", startTimeParameter, endTimeParameter, timeSpanParameter);
        }
    
        public virtual ObjectResult<sp_wx_getMonthlyProductInfoByAddressId_Result> sp_wx_getMonthlyProductInfoByAddressId(Nullable<System.DateTime> startTime, Nullable<System.DateTime> endTime, Nullable<int> address_id)
        {
            var startTimeParameter = startTime.HasValue ?
                new ObjectParameter("startTime", startTime) :
                new ObjectParameter("startTime", typeof(System.DateTime));
    
            var endTimeParameter = endTime.HasValue ?
                new ObjectParameter("endTime", endTime) :
                new ObjectParameter("endTime", typeof(System.DateTime));
    
            var address_idParameter = address_id.HasValue ?
                new ObjectParameter("address_id", address_id) :
                new ObjectParameter("address_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_wx_getMonthlyProductInfoByAddressId_Result>("sp_wx_getMonthlyProductInfoByAddressId", startTimeParameter, endTimeParameter, address_idParameter);
        }
    
        public virtual ObjectResult<sp_wx_getOrderInfo_Result> sp_wx_getOrderInfo(Nullable<System.DateTime> startTime, Nullable<System.DateTime> endTime, Nullable<int> timeSpan)
        {
            var startTimeParameter = startTime.HasValue ?
                new ObjectParameter("startTime", startTime) :
                new ObjectParameter("startTime", typeof(System.DateTime));
    
            var endTimeParameter = endTime.HasValue ?
                new ObjectParameter("endTime", endTime) :
                new ObjectParameter("endTime", typeof(System.DateTime));
    
            var timeSpanParameter = timeSpan.HasValue ?
                new ObjectParameter("timeSpan", timeSpan) :
                new ObjectParameter("timeSpan", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_wx_getOrderInfo_Result>("sp_wx_getOrderInfo", startTimeParameter, endTimeParameter, timeSpanParameter);
        }
    
        public virtual ObjectResult<sp_wx_getProductCategoryInfo_Result> sp_wx_getProductCategoryInfo(Nullable<System.DateTime> startTime, Nullable<System.DateTime> endTime)
        {
            var startTimeParameter = startTime.HasValue ?
                new ObjectParameter("startTime", startTime) :
                new ObjectParameter("startTime", typeof(System.DateTime));
    
            var endTimeParameter = endTime.HasValue ?
                new ObjectParameter("endTime", endTime) :
                new ObjectParameter("endTime", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_wx_getProductCategoryInfo_Result>("sp_wx_getProductCategoryInfo", startTimeParameter, endTimeParameter);
        }
    
        public virtual ObjectResult<sp_wx_getProductInfo_Result> sp_wx_getProductInfo(Nullable<System.DateTime> startTime, Nullable<System.DateTime> endTime, Nullable<int> timeSpan)
        {
            var startTimeParameter = startTime.HasValue ?
                new ObjectParameter("startTime", startTime) :
                new ObjectParameter("startTime", typeof(System.DateTime));
    
            var endTimeParameter = endTime.HasValue ?
                new ObjectParameter("endTime", endTime) :
                new ObjectParameter("endTime", typeof(System.DateTime));
    
            var timeSpanParameter = timeSpan.HasValue ?
                new ObjectParameter("timeSpan", timeSpan) :
                new ObjectParameter("timeSpan", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_wx_getProductInfo_Result>("sp_wx_getProductInfo", startTimeParameter, endTimeParameter, timeSpanParameter);
        }
    
        public virtual ObjectResult<sp_wx_getProductInfoByNameAndDate_Result> sp_wx_getProductInfoByNameAndDate(string pName, Nullable<System.DateTime> startTime, Nullable<System.DateTime> endTime)
        {
            var pNameParameter = pName != null ?
                new ObjectParameter("pName", pName) :
                new ObjectParameter("pName", typeof(string));
    
            var startTimeParameter = startTime.HasValue ?
                new ObjectParameter("startTime", startTime) :
                new ObjectParameter("startTime", typeof(System.DateTime));
    
            var endTimeParameter = endTime.HasValue ?
                new ObjectParameter("endTime", endTime) :
                new ObjectParameter("endTime", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_wx_getProductInfoByNameAndDate_Result>("sp_wx_getProductInfoByNameAndDate", pNameParameter, startTimeParameter, endTimeParameter);
        }
    
        public virtual ObjectResult<sp_wx_getRegionProductInfo_Result> sp_wx_getRegionProductInfo(Nullable<System.DateTime> startTime, Nullable<System.DateTime> endTime)
        {
            var startTimeParameter = startTime.HasValue ?
                new ObjectParameter("startTime", startTime) :
                new ObjectParameter("startTime", typeof(System.DateTime));
    
            var endTimeParameter = endTime.HasValue ?
                new ObjectParameter("endTime", endTime) :
                new ObjectParameter("endTime", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_wx_getRegionProductInfo_Result>("sp_wx_getRegionProductInfo", startTimeParameter, endTimeParameter);
        }
    
        public virtual ObjectResult<sp_wx_getSingleProductSaleInfoByNameAndDate_Result> sp_wx_getSingleProductSaleInfoByNameAndDate(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate, string name)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("startDate", startDate) :
                new ObjectParameter("startDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("endDate", endDate) :
                new ObjectParameter("endDate", typeof(System.DateTime));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_wx_getSingleProductSaleInfoByNameAndDate_Result>("sp_wx_getSingleProductSaleInfoByNameAndDate", startDateParameter, endDateParameter, nameParameter);
        }
    
        public virtual ObjectResult<sp_zhsettle_getGoodsDealCategoryInfo_Result> sp_zhsettle_getGoodsDealCategoryInfo(Nullable<System.DateTime> startTime, Nullable<System.DateTime> endTime, Nullable<int> tradeMode)
        {
            var startTimeParameter = startTime.HasValue ?
                new ObjectParameter("startTime", startTime) :
                new ObjectParameter("startTime", typeof(System.DateTime));
    
            var endTimeParameter = endTime.HasValue ?
                new ObjectParameter("endTime", endTime) :
                new ObjectParameter("endTime", typeof(System.DateTime));
    
            var tradeModeParameter = tradeMode.HasValue ?
                new ObjectParameter("tradeMode", tradeMode) :
                new ObjectParameter("tradeMode", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_zhsettle_getGoodsDealCategoryInfo_Result>("sp_zhsettle_getGoodsDealCategoryInfo", startTimeParameter, endTimeParameter, tradeModeParameter);
        }
    
        public virtual ObjectResult<sp_zhsettle_getGoodsDealInfo_Result> sp_zhsettle_getGoodsDealInfo(Nullable<System.DateTime> startTime, Nullable<System.DateTime> endTime, Nullable<int> tradeMode)
        {
            var startTimeParameter = startTime.HasValue ?
                new ObjectParameter("startTime", startTime) :
                new ObjectParameter("startTime", typeof(System.DateTime));
    
            var endTimeParameter = endTime.HasValue ?
                new ObjectParameter("endTime", endTime) :
                new ObjectParameter("endTime", typeof(System.DateTime));
    
            var tradeModeParameter = tradeMode.HasValue ?
                new ObjectParameter("tradeMode", tradeMode) :
                new ObjectParameter("tradeMode", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_zhsettle_getGoodsDealInfo_Result>("sp_zhsettle_getGoodsDealInfo", startTimeParameter, endTimeParameter, tradeModeParameter);
        }
    
        public virtual int P_Sys_DeleteRightByRoleId(string roleId)
        {
            var roleIdParameter = roleId != null ?
                new ObjectParameter("roleId", roleId) :
                new ObjectParameter("roleId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_Sys_DeleteRightByRoleId", roleIdParameter);
        }
    }
}
