//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLZ.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class easyuigrid
    {
        public int univgrid_id { get; set; }
        public int easyuigrid_id { get; set; }
        public string width { get; set; }
        public string height { get; set; }
        public string methord { get; set; }
        public bool fitColumns { get; set; }
        public string sortName { get; set; }
        public string sortOrder { get; set; }
        public string idField { get; set; }
        public Nullable<int> pageSize { get; set; }
        public string pageList { get; set; }
        public Nullable<bool> pagination { get; set; }
        public bool remoteSort { get; set; }
        public bool showFooter { get; set; }
        public bool striped { get; set; }
        public bool singleSelect { get; set; }
        public bool rownumbers { get; set; }
        public string onClickCell { get; set; }
        public string mod_user { get; set; }
        public System.DateTime mod_date { get; set; }
    }
}
