//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLZ.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class highchart_column
    {
        public int chartid { get; set; }
        public string field { get; set; }
        public string field_type { get; set; }
        public string field_display { get; set; }
        public string mod_user { get; set; }
        public System.DateTime mod_date { get; set; }
    }
}
