//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLZ.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class highchart
    {
        public int univgrid_id { get; set; }
        public int chartid { get; set; }
        public string width { get; set; }
        public string height { get; set; }
        public string name { get; set; }
        public string chartmode { get; set; }
        public string chart { get; set; }
        public string title { get; set; }
        public string tooltip { get; set; }
        public string xAxis { get; set; }
        public string yAxis { get; set; }
        public string plotOptions { get; set; }
        public string series { get; set; }
        public string mod_user { get; set; }
        public System.DateTime mod_date { get; set; }
    }
}
