//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLZ.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_customer_order
    {
        public int Id { get; set; }
        public string truename { get; set; }
        public string wechat_id { get; set; }
        public int totalOrder { get; set; }
        public System.DateTime time { get; set; }
        public int totalCount { get; set; }
        public decimal totalPrice { get; set; }
    }
}
