//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLZ.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_product_cat
    {
        public int id { get; set; }
        public string token { get; set; }
        public string name { get; set; }
        public string des { get; set; }
        public int parentid { get; set; }
        public string logourl { get; set; }
        public byte dining { get; set; }
        public System.DateTime time { get; set; }
        public short is_index_display { get; set; }
        public int sort { get; set; }
        public string keyword { get; set; }
    }
}
