//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLZ.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_product
    {
        public int id { get; set; }
        public short catid { get; set; }
        public short storeid { get; set; }
        public string name { get; set; }
        public decimal price { get; set; }
        public decimal oprice { get; set; }
        public decimal discount { get; set; }
        public string intro { get; set; }
        public string token { get; set; }
        public string keyword { get; set; }
        public short salecount { get; set; }
        public string logourl { get; set; }
        public byte dining { get; set; }
        public byte groupon { get; set; }
        public System.DateTime endtime { get; set; }
        public short fakemembercount { get; set; }
        public System.DateTime time { get; set; }
        public string sn { get; set; }
        public int stock { get; set; }
        public short state { get; set; }
        public short is_sell_use_stock { get; set; }
    }
}
