//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLZ.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_product_salegoods
    {
        public long id { get; set; }
        public string orderid { get; set; }
        public string sn { get; set; }
        public decimal price { get; set; }
        public int count { get; set; }
        public System.DateTime time { get; set; }
        public Nullable<int> address_id { get; set; }
    }
}
