//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLZ.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_product_cart
    {
        public long id { get; set; }
        public string token { get; set; }
        public string wecha_id { get; set; }
        public string info { get; set; }
        public short total { get; set; }
        public decimal price { get; set; }
        public System.DateTime time { get; set; }
        public byte paid { get; set; }
        public string pay_type { get; set; }
        public string truename { get; set; }
        public string orderid { get; set; }
        public Nullable<int> address_id { get; set; }
    }
}
