//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLZ.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZH_DIC_PRODUCT
    {
        public string PRODUCT_SN { get; set; }
        public string PRODUCT_ID { get; set; }
        public string PRODUCT_NAME { get; set; }
        public string LEVEL_ID { get; set; }
        public string LEVEL_NAME { get; set; }
        public string ALIAS { get; set; }
        public string ENGLISH_NAME { get; set; }
        public string REMARK { get; set; }
        public bool IS_VALID { get; set; }
        public string SHORT { get; set; }
        public string SPRODUCT_ID { get; set; }
        public string SPRODUCT_NAME { get; set; }
        public bool IS_SELECTED { get; set; }
        public string PRODUCT_INMARKET_NAME { get; set; }
        public string PRODUCT_ORDERNO { get; set; }
        public bool PRODUCT_ISVIEW { get; set; }
        public string PRODUCT_TYPE_ID { get; set; }
        public bool is_promotion { get; set; }
        public Nullable<decimal> CHARGE_RATE { get; set; }
    }
}
