//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLZ.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZH_GOODS_TYPE
    {
        public int ID { get; set; }
        public string PRODUCT_SN { get; set; }
        public string PRODUCT_NAME { get; set; }
        public string PRODUCT_TYPE_NAME { get; set; }
    }
}
