//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLZ.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZH_SETTLE_DEAL_MAIN
    {
        public decimal GOODS_CASH { get; set; }
        public decimal MANAGE_FEE { get; set; }
        public int DEAL_COUNT { get; set; }
        public long ID { get; set; }
        public System.DateTime DEAL_TIME { get; set; }
    }
}
